<div class="product attribute overview attribute-block">
    <span class="value">
        <?php
            if($block->isSetup()) {
                foreach ($block->getBlockIDs() as $blockID) {
                    echo "<div>";
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($blockID)->toHtml();
                    echo "</div>";
                }
            }
        ?>
    </span>
</div>